version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: cron
      cronjob: 5 4 16 * *
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: cron
      cronjob: 5 5 16 * *
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
